const { Buffer } = require("node:buffer")

const EVENTS = new Set(["starting", "ready", "failed"])

const notificationName = (namespace, requestID, event) => {
  if (!namespace || !requestID || !EVENTS.has(event)) {
    throw new Error("Invalid screen-share notification identity")
  }

  return `${namespace}.screen-share.${requestID}.${event}`
}

const shouldCancelPickerRequest = ({ extensionStarted, requestPending }) =>
  requestPending && !extensionStarted

const beginOnce = alreadyBegan => !alreadyBegan

const canUseNetworkThread = networkThreadStarted => networkThreadStarted

const nextUploaderState = (remainingBytes, writtenBytes) => {
  if (writtenBytes < 0) return "failed"
  return writtenBytes >= remainingBytes ? "ready" : "writing"
}

const frameMessage = ({ body, width, height, orientation }) => {
  const headers = [
    "HTTP/1.1 200 OK",
    `Content-Length: ${body.length}`,
    `Buffer-Width: ${width}`,
    `Buffer-Height: ${height}`,
    `Buffer-Orientation: ${orientation}`,
    "",
    "",
  ].join("\r\n")

  return Buffer.concat([Buffer.from(headers, "ascii"), body])
}

const parseFrameMessage = message => {
  const boundary = message.indexOf("\r\n\r\n")
  if (boundary < 0) throw new Error("Incomplete screen-share response")

  const headerLines = message
    .subarray(0, boundary)
    .toString("ascii")
    .split("\r\n")
  if (headerLines.shift() !== "HTTP/1.1 200 OK") {
    throw new Error("Screen-share transport requires an HTTP response frame")
  }

  const headers = new Map(
    headerLines.map(line => {
      const separator = line.indexOf(":")
      return [line.slice(0, separator), line.slice(separator + 1).trim()]
    }),
  )
  const body = message.subarray(boundary + 4)
  if (body.length !== Number(headers.get("Content-Length"))) {
    throw new Error("Screen-share frame length mismatch")
  }

  return {
    body,
    width: Number(headers.get("Buffer-Width")),
    height: Number(headers.get("Buffer-Height")),
    orientation: Number(headers.get("Buffer-Orientation")),
  }
}

const nativeHeader =
  namespace => `// Generated by withIosBroadcastExtension.js. Do not edit.
#import <Foundation/Foundation.h>

static NSString *const ScreenShareNotificationNamespace = @"${namespace}";
static NSString *const ScreenShareRequestIDKey = @"RTCScreenShareRequestID";
#define ScreenShareHTTPStatusCode 200
#define ScreenShareContentLengthHeader CFSTR("Content-Length")
#define ScreenShareWidthHeader CFSTR("Buffer-Width")
#define ScreenShareHeightHeader CFSTR("Buffer-Height")
#define ScreenShareOrientationHeader CFSTR("Buffer-Orientation")

static inline NSString *ScreenShareNotificationName(NSString *requestID, NSString *event) {
    return [NSString stringWithFormat:@"%@.screen-share.%@.%@",
                                      ScreenShareNotificationNamespace, requestID, event];
}

// -1 is failed, 0 is still writing, and 1 is ready for another frame.
static inline NSInteger ScreenShareStateAfterWrite(NSUInteger remainingBytes, NSInteger writtenBytes) {
    if (writtenBytes < 0) return -1;
    return (NSUInteger)writtenBytes >= remainingBytes ? 1 : 0;
}

static inline BOOL ScreenShareBeginOnce(BOOL *alreadyBegan) {
    if (*alreadyBegan) return NO;
    *alreadyBegan = YES;
    return YES;
}

static inline BOOL ScreenShareCanUseNetworkThread(BOOL networkThreadStarted) {
    return networkThreadStarted;
}

static inline BOOL ScreenShareShouldCancelPickerRequest(BOOL requestPending, BOOL extensionStarted) {
    return requestPending && !extensionStarted;
}
`

module.exports = {
  frameMessage,
  beginOnce,
  canUseNetworkThread,
  nativeHeader,
  nextUploaderState,
  notificationName,
  parseFrameMessage,
  shouldCancelPickerRequest,
}
